server:
  port: 8082
spring:
  application.name: api-auth
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  security:
    oauth2:
      client:
        max-request-size: 102400
logging:
  level:
    root: DEBUG
    org:
      springframework:
        security:
          oauth2: DEBUG
